name: Keploy API Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start API server
        run: |
          nohup npm start & # Run in background
          sleep 10 # Give the server time to start

      - name: Download Keploy binary
        run: |
          curl -fL https://github.com/keploy/keploy/releases/download/v2.6.14/keploy_linux_amd64.tar.gz -o keploy_linux_amd64.tar.gz
          tar -xzf keploy_linux_amd64.tar.gz
          chmod +x keploy
          file keploy
          sudo mv keploy /usr/local/bin/

      - name: Verify Keploy binary
        run: |
          ls -l /usr/local/bin/keploy # Check file existence and permissions
          file /usr/local/bin/keploy # Check file type

      - name: Debug Keploy binary
        run: |
          echo "PATH is: $PATH"
          which keploy || echo "keploy not in PATH"
          ls -l /usr/local/bin/keploy || echo "keploy not in /usr/local/bin"
          file /usr/local/bin/keploy || echo "file type check failed"

      - name: Run Keploy tests
        run: |
          keploy test --proxy-port 8080
